### ISSUE TITLE
repository mockit-client not found

### ISSUE THREAD

**Issue by fliu2476** [boyney123/mockit#18]
## What you did:
- chmod the file
- try again

## What happened:

```
Successfully built f693cc17ca19
Creating network "mockit_default" with the default driver
Pulling mockit-client (mockit-client:latest)...
ERROR: repository mockit-client not found: does not exist or no pull access
bogon:mockit xxxx$ 
```

## Problem description:

docker image (mockit-client) not exist

**Comment by boyney123** [comment]
Hey @fliu2476 

Can you let me know the steps to reproduce this?

Did you run `sh build-and-start.sh`? That should build and tag the images.

**Comment by fliu2476** [comment]
> Can you let me know the steps to reproduce this?

1.  git clone xxxx
2. cd mockit && sh build-and-start.sh

> Did you run `sh build-and-start.sh`? That should build and tag the images.

yes, I got error when run this command

### Environment
- macOS Mojave 10.14.4
- docker:  17.03.1-ce-rc1-mac3 (15924)

**Comment by boyney123** [comment]
I'm not sure really, as it's working for me. 

I have just merged #19 which might help? Can you try and get `latest`? and see if you still get the issue?

**Comment by fliu2476** [comment]
Thanks a lot. Fixed the error after updating latest code.

### Another error 

```
bogon:mockit xxx$ docker-compose up -d
Building mockit-client
Step 1/8 : FROM node:11.14.0-alpine as build-deps
ERROR: Service 'mockit-client' failed to build: Error parsing reference: "node:11.14.0-alpine as build-deps" is not a valid repository/tag: invalid reference format
```
Anyway, its ok now,  my solution is change ```FROM node:11.14.0-alpine as build-deps``` to ```FROM node:11.14.0-alpine``` in this [line](https://github.com/boyney123/mockit/blob/76c8efcafa19032b100d81451d9523b813262e1b/client/Dockerfile#L1).

**Comment by boyney123** [comment]
Thanks for this @fliu2476 and your patience. Yeah I'm not too sure why I added `build-deps` so I will be removing that in a PR 👍

**Comment by boyney123** [comment]
Thanks for taking the time to raise the issue and comment back 👍 .

I have added you to our contributors 🎉 

![image](https://user-images.githubusercontent.com/3268013/56862651-08393d00-69a5-11e9-8394-7bf9bdc010bf.png)

**Comment by boyney123** [comment]
#32 merged in
