### ISSUE TITLE
clarify scope of project

### ISSUE THREAD

**Issue by wohlben** [boyney123/mockit#20]
> Stop wasting time mocking APIs. MockIt gives you an interface to configure and create REAL mocked end points for your applications

This is sadly untrue, as mockit only supports  JSON APIs. Not every service gives us JSON APIs, despite it being 2019...

There is a funny bug in your frontend btw. If you copy-paste html tags with style into the "response" field, your app will try to render it. :)
```html
<!-- try it  yourself -->
<div style='width: 500px; background-color: red;'>Hey you!</div>
```

**Comment by boyney123** [comment]
> This is sadly untrue, as mockit only supports JSON APIs. Not every service gives us JSON APIs, despite it being 2019...

Yeah, guess not, guess if people want to support anything else they could just fork and make the relevant changes.

The frontend bug is an interesting one! thanks, il raise another issue for that.

**Comment by boyney123** [comment]
Closing this for now, will raise another linking back to this.
