### ISSUE TITLE
Unable to get started

### ISSUE THREAD

**Issue by JDansercoer** [boyney123/mockit#27]
## What you did:

Followed the docs.
Well, both versions of the docs, since the site and the readme have different 'Getting started' steps.

#### Following the [docs](https://mockit.netlify.com/docs/getting-started/installation)

`sh: build-and-start.sh: No such file or directory`

#### Following the Github readme

`Step 5/9 : COPY package-lock.json .
ERROR: Service 'mockit-server' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder079289765/package-lock.json: no such file or directory`

## Problem description:

I would love to give this a chance, but am unable.
Not sure if this is me missing an 'obvious' but undocumented step, or if it's something that's missing in the repo.

**Comment by boyney123** [comment]
Hey @JDansercoer 

Sorry, I merged #19 yesterday, thought I had already updated the docs, but they did not push up for some reason.

They are now updated, and also live.

You need to run `cd mockit && docker-compose up -d`

Let me know if that works for you

**Comment by JDansercoer** [comment]
Hi @boyney123,

As noted in my OP, I had also followed the Github readme, which indeed correctly states the `docker-compose up -d` command.

Unfortunately, that fails at step 5

`Step 5/9 : COPY package-lock.json . ERROR: Service 'mockit-server' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder079289765/package-lock.json: no such file or directory`

**Comment by JDansercoer** [comment]
Allright, so I just went into `server` folder, and ran `npm install` there, since it appears the `package-lock.json` isn't present in the directory.

So after running the command again, I got past step 5.

However, I'm getting a new error

`Creating mockit_mockit-server_1 ... 
Creating mockit_mockit-routes_1 ... error
Creating mockit_mockit-client_1 ... 

Creating mockit_mockit-server_1 ... done
outes_1 (c34699f6a7f7ebe25daadcb35cdf34f6ca4eadfb857124acbba904cf4bd2fec8): Error starting userland proxy: Bind for 0.0.0.0:3000 failed: port is aCreating mockit_mockit-client_1 ... done

ERROR: for mockit-routes  Cannot start service mockit-routes: driver failed programming external connectivity on endpoint mockit_mockit-routes_1 (c34699f6a7f7ebe25daadcb35cdf34f6ca4eadfb857124acbba904cf4bd2fec8): Error starting userland proxy: Bind for 0.0.0.0:3000 failed: port is already allocated`

**Comment by JDansercoer** [comment]
After opening my eyes and reading the error message, I figured out I already had something running on that port. Stopping my service on that port and re-running the command made it all work!

**Comment by boyney123** [comment]
Should be fixed in #28

**Comment by boyney123** [comment]
Thanks for the details and info @JDansercoer
