### ISSUE TITLE
Add lint for this project

### ISSUE THREAD

**Issue by hong4rc** [boyney123/mockit#34]
I don't sure that I can't know your code style.
(Maybe you use 4 space and 2 space in this project)

So can you use linter for this project(example: `eslint`)?

**Comment by boyney123** [comment]
Yeah great idea, I missed this out. I will get something in 👍

**Comment by moh3n9595** [comment]
I create a [PR](https://github.com/boyney123/mockit/pull/75) that can resolve the lint problem

**Comment by boyney123** [comment]
Sorry it's taken so long, if any1 is interested I added prettier into the project.
