### ISSUE TITLE
Featuring mockit in Docusaurus

### ISSUE THREAD

**Issue by NishealJ** [boyney123/mockit#36]
Hello, we would like to feature your project to the Docusaurus users page. 
Would that be ok? Also can you provide your logo?

More info about this [here](https://github.com/facebook/Docusaurus/issues/1080)

**Comment by boyney123** [comment]
That sounds great @NishealJ!

Here is the logo.

![image](https://user-images.githubusercontent.com/3268013/56882103-83a8f600-6a5a-11e9-9a5c-291e25b6d5f8.png)

Do you want me to PR it into Docusaurus? Or are you going to do that?

**Comment by Hongarc** [comment]
@boyney123 logo should same this 
![Screenshot](https://user-images.githubusercontent.com/19208123/56884825-24b4a280-6a95-11e9-8ac0-44da3c9b4793.png)

**Comment by NishealJ** [comment]
Hi @boyney123 & @Hongarc ,
I'll raised a PR, second logo looks fine :)
Thanks !

**Comment by Hongarc** [comment]
@NishealJ good job.
Done in facebook/Docusaurus#1415.

You should close this issue.

**Comment by NishealJ** [comment]
Hi, 
has been added [here](https://docusaurus.io/en/users) 
Thanks !
