### ISSUE TITLE
Use HTTP for git clone instead of SSH

### ISSUE THREAD

**Issue by de314** [boyney123/mockit#38]
## What you did:

Copy-pasta from https://mockit.netlify.com/docs/getting-started/installation

`git clone git@github.com:boyney123/mockit.git`

## What happened:

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```

## Problem description:

I obviously do not have SSH access to your repo

## Suggested solution:

Change documentation example to `git clone https://github.com/boyney123/mockit.git`

**Comment by de314** [comment]
TIL I have no clue how Github issues work linking #39 

https://github.com/boyney123/mockit/pull/39

**Comment by boyney123** [comment]
Thanks @de314 !
