### ISSUE TITLE
Add the ability to set response headers per endpoint

### ISSUE THREAD

**Issue by nodesocket** [boyney123/mockit#4]
Add the ability to specify key => value response headers per endpoint.

**Comment by boyney123** [comment]
Great idea @nodesocket , I will add it on the TODO list, and hopefully, get something out this week

**Comment by boyney123** [comment]
This might be simular to #23 .

Maybe the UI can have some key value pairs that are captured and sent.

**Comment by boyney123** [comment]
![image](https://user-images.githubusercontent.com/3268013/56618663-33c1cd80-661b-11e9-8b25-3efef89e8890.png)

Started to implement it, just working on the small details and maybe some validation.

**Comment by nodesocket** [comment]
@boyney123 awesome. 👍  One edge case, what happens if I put a header key and value that is outputted by the server already? Example: `Server: my-foo-server`.

**Comment by mu99y** [comment]
@boyney123 Awesome 👍

**Comment by boyney123** [comment]
![image](https://user-images.githubusercontent.com/3268013/57103384-81c28980-6d1d-11e9-8f42-83c22cd3eb94.png)

Been working abit on this feature, hopefully, get it live this week 👍 

> One edge case, what happens if I put a header key that is outputted by the server already? Example: Content-Type: text/plain.

I will test this and see what happens, Im guessing something will just get overridden, but il check it out!

**Comment by boyney123** [comment]
I'm happy to share with you that this feature is now live with MockIt 1.1.0 🎉 

Head over to https://mockit.netlify.com/blog/ to find out more details

https://mockit.netlify.com/docs/routes/route-features#response-headers

Thanks for the idea @nodesocket
