### ISSUE TITLE
Enabling grouped routes causes React errors

### ISSUE THREAD

**Issue by ryanjw-exp** [boyney123/mockit#50]
## What you did:
Enabled 'grouped routes' option

## What happened:
<img width="1028" alt="Screen Shot 2019-05-30 at 16 31 52" src="https://user-images.githubusercontent.com/50908976/58644463-38079780-82f9-11e9-8e7c-95d14feb0f9d.png">

## Problem description:
React crashes prevent further use of app.

## Suggested solution:
Going into routes.json and turning `groupedRoutes` back to `false` seems to fix.

**Comment by boyney123** [comment]
Thanks for sharing this @ryanjw-exp 

Can you share with me your `route.json` file? See I can replicate this thing locally.

**Comment by haythemgara** [comment]
hello, I am using mockIt and this problem still present :(
