### ISSUE TITLE
better install script

### ISSUE THREAD

**Issue by amovah** [boyney123/mockit#51]
in your install script, you used npm install. so there is a little difference between npm install and npm ci. https://stackoverflow.com/questions/52499617/what-is-the-difference-between-npm-install-and-npm-ci, according to this, it's better to use npm ci when we have package-lock.json for better performances and preventing re-generate package-lock.json in another systems.

if you agree with me, I would like to send you a PR for that.

**Comment by boyney123** [comment]
Hey @amovah 

We currently use `npm ci` in the docker file, but I guess for local development anybody could use `npm ci` or `npm install`. If you want to add it to the docs to suggest for people that might be good?
