### ISSUE TITLE
missed dependency

### ISSUE THREAD

**Issue by amovah** [boyney123/mockit#52]
## What you did:

in mockit/client, I tried to run `npm start` after installing dependencies.

## What happened:

https://pastebin.com/WnHu0ycK

## Problem description:
 
npm install failed.

## Suggested solution:

I've installed node-sass through npm, and problems goes away. I'm not sure about it, but maybe it cause because you missed node-sass in dependencies.

**Comment by webdevium** [comment]
Checked on latest npm, absolute clear installation. All right, no errors. Which version of npm you use?

**Comment by amovah** [comment]
npm version 6.9.0

**Comment by amovah** [comment]
it seems, it's a npm issue with node-gyp and I've fixed it.
