### ISSUE TITLE
Linting warnings are shown in console

### ISSUE THREAD

**Issue by aaronmcadam** [boyney123/mockit#55]
First of all, thanks for this, I'm really liking it so far!

## What you did:

Booted the client. 

## What happened:

![Google Chrome 2019-06-28 at 13 28 28@2x](https://user-images.githubusercontent.com/37928/60342238-cfb7de80-99a8-11e9-8991-92a56f9149ee.png)

## Problem description:

This creates just a bit of noise

## Suggested solution:

I appreciate that this warnings probably slipped through. Easily done!

**Comment by MCRayRay** [comment]
I'll work on cleaning these up.
