### ISSUE TITLE
Save changes does not do anything

### ISSUE THREAD

**Issue by snj07** [boyney123/mockit#74]
## What you did: 
I tried to create/modify a route

## What happened: Nothing happens. 
It neither creates a new route not generates an error message. I have tried with the latest version.

**Comment by ApolloTang** [comment]
same here, occasionally it save but it is very slow

**Comment by boyney123** [comment]
@snj07 thanks for raising an issue.

I just pulled down the latest code and everything seems to be working from my end.

What operating system are you using? Out of interest, also what browser?

**Comment by snj07** [comment]
I am using Ubuntu 18 LTS. I tried in both Mozilla and Chrome. Everything is running inside the container.

**Comment by BenFisher** [comment]
I'm bumping into this as well. I am running Mockit in docker containers.

**Comment by boyney123** [comment]
Sorry guys, I'm going to close this for now. Tried everything my side and things seem OK, unless you want to try and debug and help me figure it out? I'm not really sure what more use I can be.
