### ISSUE TITLE
Mock routes are throwing errors.

### ISSUE THREAD

**Issue by pratheekhegde** [boyney123/mockit#8]
What you did:
- Turned on Chaos Monkey from the settings.
- Clicked on any of the example mock routes.

What happened:
- Opening the mock route threw an error.
![image](https://user-images.githubusercontent.com/11031124/56466028-635cb400-6428-11e9-88a4-f950521496fe.png)

Problem description:
- `hitByMonkey` util method is defined as a commonjs export but imported as an ES6 import in `mockit-routes/src/middlewares/chaos-monkey/index.js`

Suggested solution:
- Change `const { hitByMonkey } = require("./util");` to `const hitByMonkey = require("./util");`
- Or any other way.

**Comment by boyney123** [comment]
Thanks for raising this @pratheekhegde, I have put in a fix in this PR #11

**Comment by boyney123** [comment]
Merged in, thanks again for raising the issue @pratheekhegde 👍

**Comment by pratheekhegde** [comment]
You are welcome. 😃
