### ISSUE TITLE
SSL & corporate network

### ISSUE THREAD

**Issue by ludovic-pourrat** [boyney123/mockit#83]
In order to support building the compose images within a corporate network, a set of .nmprc files must be added to the client / server / mockit-routes with "strict-ssl=false". Then the .npmrc file must be mounted prior to execute the stage npm ci. 

See - https://medium.com/@iffi33/dealing-with-ssl-authentication-on-a-secure-corporate-network-pip-conda-git-npm-yarn-bower-73e5b93fd4b2

**Comment by boyney123** [comment]
Merge request open, going to talk there.
