### ISSUE TITLE
Resolving security vulnerabilities in dependent packages

### ISSUE THREAD

**Issue by lirantal** [boyney123/mockit#9]
Really nice work on this project David! Congrats 🎉

## What you did:
- I forked the repository
- Connected it with snyk.io
- Observed the security scan results

## What happened:
Great stuff here: Dockerfile uses alpine ✅ Server-side code doesn't use any packages with known vulnerabilities ✅

However I found several vulnerabilities on the frontend related code:

![image](https://user-images.githubusercontent.com/316371/56466396-36a1a000-641a-11e9-82e1-46621ed7de43.png)

## Problem description:

When cloning the project for personal use, Snyk alerts me of security vulnerabilities.

## Suggested solution:

Some of the security vulnerabilities reported on dependent packages can be resolved by using newer versions of them (so an update to the lockfile is needed).

**Comment by boyney123** [comment]
Thanks @lirantal 🙇 👍 

I have attempted to fix it in # 13, would be great if you could review it?
